FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install net-tools -y
RUN apt-get install curl -y
RUN apt-get install nmap -y
RUN apt-get install iputils-ping -y

CMD while true; do echo me quedo encendida;	sleep 1000000; done